#ASTEROID
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#LINE
LINE_WIDTH = 2

#PLAYER
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
## shooting
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_SHOOT_SPEED = 500
SHOT_RADIUS = 5

#SCREEN
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720